api_platform:

    # The title of the API.
    title: 'BLACKSHEEP VAN - API'

    # The description of the API.
    description: 'Accès aux webservices'

    # The version of the API.
    version: '1.0.0'

    # Set this to false if you want Webby to disappear.
    show_webby: false