<?php

namespace ContainerB5HZDPj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ContentRepository' shared autowired service.
     *
     * @return \App\Repository\ContentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ContentRepository'] = new \App\Repository\ContentRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
