<?php

namespace ContainerTfBNE3f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFeezqDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gFeezqD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gFeezqD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campervan' => ['privates', '.errored..service_locator.gFeezqD.App\\Entity\\Campervan', NULL, 'Cannot autowire service ".service_locator.gFeezqD": it needs an instance of "App\\Entity\\Campervan" but this type has been excluded in "config/services.yaml".'],
        ], [
            'campervan' => 'App\\Entity\\Campervan',
        ]);
    }
}
