<?php

namespace ContainerTfBNE3f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FRwaoZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fRwao_Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fRwao_Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adresse' => ['privates', '.errored..service_locator.fRwao_Z.App\\Entity\\Adresse', NULL, 'Cannot autowire service ".service_locator.fRwao_Z": it needs an instance of "App\\Entity\\Adresse" but this type has been excluded in "config/services.yaml".'],
            'adresseRepository' => ['privates', 'App\\Repository\\AdresseRepository', 'getAdresseRepositoryService', true],
        ], [
            'adresse' => 'App\\Entity\\Adresse',
            'adresseRepository' => 'App\\Repository\\AdresseRepository',
        ]);
    }
}
