<?php

namespace ContainerUy2rxkU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hrx84NlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hrx84Nl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hrx84Nl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agence' => ['privates', '.errored..service_locator.hrx84Nl.App\\Entity\\Agence', NULL, 'Cannot autowire service ".service_locator.hrx84Nl": it needs an instance of "App\\Entity\\Agence" but this type has been excluded in "config/services.yaml".'],
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
        ], [
            'agence' => 'App\\Entity\\Agence',
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
        ]);
    }
}
