<?php

namespace ContainerUy2rxkU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_UxcollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.ux-collection' shared service.
     *
     * @return \Arkounay\Bundle\UxCollectionBundle\Form\UxCollectionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'arkounay'.\DIRECTORY_SEPARATOR.'ux-collection'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'UxCollectionType.php';

        return $container->privates['form.ux-collection'] = new \Arkounay\Bundle\UxCollectionBundle\Form\UxCollectionType();
    }
}
