<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SM5iZpOService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.sM5iZpO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sM5iZpO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'assurance' => ['privates', '.errored..service_locator.sM5iZpO.App\\Entity\\Assurance', NULL, 'Cannot autowire service ".service_locator.sM5iZpO": it needs an instance of "App\\Entity\\Assurance" but this type has been excluded in "config/services.yaml".'],
            'assuranceRepository' => ['privates', 'App\\Repository\\AssuranceRepository', 'getAssuranceRepositoryService', true],
        ], [
            'assurance' => 'App\\Entity\\Assurance',
            'assuranceRepository' => 'App\\Repository\\AssuranceRepository',
        ]);
    }
}
