<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MNXHVOvService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.MNXHVOv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MNXHVOv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'content' => ['privates', '.errored..service_locator.MNXHVOv.App\\Entity\\Content', NULL, 'Cannot autowire service ".service_locator.MNXHVOv": it needs an instance of "App\\Entity\\Content" but this type has been excluded in "config/services.yaml".'],
        ], [
            'content' => 'App\\Entity\\Content',
        ]);
    }
}
