<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdresseRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AdresseRepository' shared autowired service.
     *
     * @return \App\Repository\AdresseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AdresseRepository'] = new \App\Repository\AdresseRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
