<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdresse2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.fRwao_Z.App\Entity\Adresse' shared service.
     *
     * @return \App\Entity\Adresse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fRwao_Z": it needs an instance of "App\\Entity\\Adresse" but this type has been excluded in "config/services.yaml".');
    }
}
