<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgenceAdresseRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AgenceAdresseRepository' shared autowired service.
     *
     * @return \App\Repository\AgenceAdresseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AgenceAdresseRepository'] = new \App\Repository\AgenceAdresseRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
