<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ContentType' shared autowired service.
     *
     * @return \App\Form\ContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ContentType'] = new \App\Form\ContentType();
    }
}
