<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.87lbYIT.App\Entity\Content' shared service.
     *
     * @return \App\Entity\Content
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.87lbYIT": it needs an instance of "App\\Entity\\Content" but this type has been excluded in "config/services.yaml".');
    }
}
