<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCropControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Arkounay\Bundle\UxMediaBundle\Controller\CropController' shared autowired service.
     *
     * @return \Arkounay\Bundle\UxMediaBundle\Controller\CropController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Arkounay\\Bundle\\UxMediaBundle\\Controller\\CropController'] = $instance = new \Arkounay\Bundle\UxMediaBundle\Controller\CropController(($container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FilemanagerService'] ?? $container->load('getFilemanagerServiceService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('Arkounay\\Bundle\\UxMediaBundle\\Controller\\CropController', $container));

        return $instance;
    }
}
