<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_UxmediaService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.ux-media' shared service.
     *
     * @return \Arkounay\Bundle\UxMediaBundle\Form\UxMediaType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.ux-media'] = new \Arkounay\Bundle\UxMediaBundle\Form\UxMediaType();
    }
}
