<?php

namespace Container2Zsv8xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilemanagerServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Artgris\Bundle\FileManagerBundle\Service\FilemanagerService' shared autowired service.
     *
     * @return \Artgris\Bundle\FileManagerBundle\Service\FilemanagerService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FilemanagerService'] = new \Artgris\Bundle\FileManagerBundle\Service\FilemanagerService($container->parameters['artgris_file_manager'], $container);
    }
}
