<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5HZDPj\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5HZDPj/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerB5HZDPj.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerB5HZDPj\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerB5HZDPj\App_KernelProdContainer([
    'container.build_hash' => 'B5HZDPj',
    'container.build_id' => 'e0f3fd32',
    'container.build_time' => 1676456182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5HZDPj');
