<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.61b1725c.js',
                '/build/751.552fdddd.js',
                '/build/app.0784ad4d.js',
            ],
            'css' => [
                '/build/app.ca113208.css',
            ],
        ],
    ],
],

]];
