<?php

namespace ContainerA7qroHN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_87lbYITService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.87lbYIT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.87lbYIT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'content' => ['privates', '.errored..service_locator.87lbYIT.App\\Entity\\Content', NULL, 'Cannot autowire service ".service_locator.87lbYIT": it needs an instance of "App\\Entity\\Content" but this type has been excluded in "config/services.yaml".'],
            'contentRepository' => ['privates', 'App\\Repository\\ContentRepository', 'getContentRepositoryService', true],
        ], [
            'content' => 'App\\Entity\\Content',
            'contentRepository' => 'App\\Repository\\ContentRepository',
        ]);
    }
}
