<?php

namespace ContainerA7qroHN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCropControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Arkounay\Bundle\UxMediaBundle\Controller\CropController' shared autowired service.
     *
     * @return \Arkounay\Bundle\UxMediaBundle\Controller\CropController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'arkounay'.\DIRECTORY_SEPARATOR.'ux-media'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CropController.php';

        $container->services['Arkounay\\Bundle\\UxMediaBundle\\Controller\\CropController'] = $instance = new \Arkounay\Bundle\UxMediaBundle\Controller\CropController(($container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FilemanagerService'] ?? $container->getFilemanagerServiceService()));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('Arkounay\\Bundle\\UxMediaBundle\\Controller\\CropController', $container));

        return $instance;
    }
}
