<?php

namespace ContainerI5yuEQu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7bzWcCZService extends App_KernelPrpdDebugContainer
{
    /**
     * Gets the private '.service_locator.7bzWcCZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7bzWcCZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agence' => ['privates', '.errored..service_locator.7bzWcCZ.App\\Entity\\Agence', NULL, 'Cannot autowire service ".service_locator.7bzWcCZ": it needs an instance of "App\\Entity\\Agence" but this type has been excluded in "config/services.yaml".'],
        ], [
            'agence' => 'App\\Entity\\Agence',
        ]);
    }
}
