<?php

namespace ContainerI5yuEQu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgence2Service extends App_KernelPrpdDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hrx84Nl.App\Entity\Agence' shared service.
     *
     * @return \App\Entity\Agence
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hrx84Nl": it needs an instance of "App\\Entity\\Agence" but this type has been excluded in "config/services.yaml".');
    }
}
