<?php

namespace ContainerI5yuEQu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampervanService extends App_KernelPrpdDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..C7T_vF.App\Entity\Campervan' shared service.
     *
     * @return \App\Entity\Campervan
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..C7T_vF": it needs an instance of "App\\Entity\\Campervan" but this type has been excluded in "config/services.yaml".');
    }
}
