<?php

namespace ContainerI5yuEQu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileTypeServiceService extends App_KernelPrpdDebugContainer
{
    /**
     * Gets the private 'Artgris\Bundle\FileManagerBundle\Service\FileTypeService' shared autowired service.
     *
     * @return \Artgris\Bundle\FileManagerBundle\Service\FileTypeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'artgris'.\DIRECTORY_SEPARATOR.'filemanager-bundle'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FileTypeService.php';

        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FileTypeService'])) {
            return $container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FileTypeService'];
        }
        $b = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FileTypeService'])) {
            return $container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FileTypeService'];
        }

        return $container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FileTypeService'] = new \Artgris\Bundle\FileManagerBundle\Service\FileTypeService($a, $b);
    }
}
