<?php

namespace ContainerI5yuEQu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilemanagerServiceService extends App_KernelPrpdDebugContainer
{
    /**
     * Gets the private 'Artgris\Bundle\FileManagerBundle\Service\FilemanagerService' shared autowired service.
     *
     * @return \Artgris\Bundle\FileManagerBundle\Service\FilemanagerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'artgris'.\DIRECTORY_SEPARATOR.'filemanager-bundle'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FilemanagerService.php';

        return $container->privates['Artgris\\Bundle\\FileManagerBundle\\Service\\FilemanagerService'] = new \Artgris\Bundle\FileManagerBundle\Service\FilemanagerService($container->parameters['artgris_file_manager'], $container);
    }
}
