<?php

namespace ContainerN9Ca4rU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MNXHVOv.App\Entity\Content' shared service.
     *
     * @return \App\Entity\Content
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MNXHVOv": it needs an instance of "App\\Entity\\Content" but this type has been excluded in "config/services.yaml".');
    }
}
