<?php

namespace ContainerN9Ca4rU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_UxmediaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.ux-media' shared service.
     *
     * @return \Arkounay\Bundle\UxMediaBundle\Form\UxMediaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'arkounay'.\DIRECTORY_SEPARATOR.'ux-media'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'UxMediaType.php';

        return $container->privates['form.ux-media'] = new \Arkounay\Bundle\UxMediaBundle\Form\UxMediaType();
    }
}
