<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI5yuEQu\App_KernelPrpdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI5yuEQu/App_KernelPrpdDebugContainer.php') {
    touch(__DIR__.'/ContainerI5yuEQu.legacy');

    return;
}

if (!\class_exists(App_KernelPrpdDebugContainer::class, false)) {
    \class_alias(\ContainerI5yuEQu\App_KernelPrpdDebugContainer::class, App_KernelPrpdDebugContainer::class, false);
}

return new \ContainerI5yuEQu\App_KernelPrpdDebugContainer([
    'container.build_hash' => 'I5yuEQu',
    'container.build_id' => '23295b26',
    'container.build_time' => 1677673360,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI5yuEQu');
