<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN9Ca4rU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN9Ca4rU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN9Ca4rU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN9Ca4rU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN9Ca4rU\App_KernelDevDebugContainer([
    'container.build_hash' => 'N9Ca4rU',
    'container.build_id' => 'dd2828da',
    'container.build_time' => 1677677481,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN9Ca4rU');
