<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA7qroHN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA7qroHN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA7qroHN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA7qroHN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA7qroHN\App_KernelDevDebugContainer([
    'container.build_hash' => 'A7qroHN',
    'container.build_id' => '654222ac',
    'container.build_time' => 1677691233,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA7qroHN');
